### ISSUE TITLE
playground opens on 3000

### ISSUE THREAD

**Issue by wesbos** [wesbos/Advanced-React#49]
it should open on 4444

need to investigate why

**Comment by wesbos** [comment]
this has something to do with the playground command in package.json

**Comment by wesbos** [comment]
easyyy fix

**Comment by LTTaylor** [comment]
@wesbos - This change seems to break the `npm run dev` script for me.

If I remove the `--port 4444` from the playground script in `package.json` then everything runs fine but when it's there I receive the following error:

```bash
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle sick-fits-backend@~predev: sick-fits-backend@
6 info lifecycle sick-fits-backend@~dev: sick-fits-backend@
7 verbose lifecycle sick-fits-backend@~dev: unsafe-perm in lifecycle true
8 verbose lifecycle sick-fits-backend@~dev: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Lee\projects\Advanced-React\sick-fits\backend\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\Microsoft VS Code Insiders\bin;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Git\cmd;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\Lee\AppData\Local\scoop\shims;C:\Users\Lee\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Sublime Text 3;C:\Users\Lee\AppData\Local\GitHub\PortableGit_f02737a78695063deace08e96d5042710d3e32db\cmd\git.exe;C:\Users\Lee\AppData\Local\GitHub\PortableGit_f02737a78695063deace08e96d5042710d3e32db\cmd\git.exe;C:\Program Files\Microsoft VS Code Insiders\bin;C:\Users\Lee\AppData\Roaming\npm;C:\Users\Lee\AppData\Local\Programs\Microsoft VS Code Insiders\bin;C:\Users\Lee\AppData\Local\Yarn\bin;
9 verbose lifecycle sick-fits-backend@~dev: CWD: C:\Users\Lee\projects\Advanced-React\sick-fits\backend
10 silly lifecycle sick-fits-backend@~dev: Args: [ '/d /s /c', 'npm-run-all --parallel debug playground' ]
11 silly lifecycle sick-fits-backend@~dev: Returned: code: 1  signal: null
12 info lifecycle sick-fits-backend@~dev: Failed to exec dev script
13 verbose stack Error: sick-fits-backend@ dev: `npm-run-all --parallel debug playground`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid sick-fits-backend@
15 verbose cwd C:\Users\Lee\projects\Advanced-React\sick-fits\backend
16 verbose Windows_NT 10.0.17760
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error sick-fits-backend@ dev: `npm-run-all --parallel debug playground`
22 error Exit status 1
23 error Failed at the sick-fits-backend@ dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by papascott** [comment]
Hmm, with "npm run dev" are both graphql-yoga and graphql-cli running playgrounds at the same time?

**Comment by wesbos** [comment]
I think you might be right - ill investigate it a bit more - thanks for the reports :)

**Comment by dangdennis** [comment]
My current solution:
```
scripts:  { "dev": "npm-run-all --parallel debug" } // dont run playground script
```
To have the playground generated from `createServer()`, I pass in an extra option.
```
server.start(
    {   
        cors: {
            credentials: true,
            origin: process.env.FRONTEND_URL
        },
        playground: '/playground',
    },
    data => {
        console.log(`Server is now running on port http://localhost:${data.port}`);
    }
);
```
I'm only video 13, so not sure if this causes issues later on. One caveat, playground doesn't automatically openin a new browser tab using this method.

**Comment by wesbos** [comment]
thanks everyone- turns out the playground script isn't needed at all - I just removed it
